### ISSUE TITLE
Installing "admonition@1.0.1" failed

### ISSUE THREAD

**Issue by chittyren** [libeanim/inkdrop-admonition#8]
Hello,

I've run into an error while attempting to install this plugin to Inkdrop.  Below is an edited screengrab of the error.
![image](https://user-images.githubusercontent.com/1612518/97064948-f0ca1880-1577-11eb-86d5-2aa98f48ceb7.png)

**OS & Inkdrop version:**  

Windows 10.0.19041
Inkdrop 5.1.1

Please let me know if there is any further information I can provide!  I appreciate any insights anyone might have.

Thank you in advance!

**Comment by chittyren** [comment]
Following up.  The plugin installs successfully via ipm command, no issues.  The error only occurs when attempting to install the plugin via the GUI.

**Comment by libeanim** [comment]
Cool, thanks for letting me know. :+1: 

I upgraded the dependencies so it should work via the GUI now too.
